### ISSUE TITLE
How did you actually get it to work?

### ISSUE THREAD

**Issue by Ravenclaw968** [skellock/expo-with-ignite#2]
How did you have expo effectively run an ignite app?

**Comment by skellock** [comment]
By removing all the native dependencies in ignite.

**Comment by Fr33maan** [comment]
That's sad your first code commit touch any simple file :(
Could we have something to reproduce with new ignite versions ?
I don't even succeed in starting this project, there isn't any scripts in package.json.  
Could you provide some additional information please ?

I tried
```
git clone https://github.com/skellock/expo-with-ignite.git
cd expo-with-ignite
npm install
```
`npm start` does nothing

**Comment by skellock** [comment]
This project uses expo. Have you tried using their Xde?

Another thing you can do is start a new expo project, then copy these files over.

This repo was me just playing around to get them to work together. Having a little fun.

**Comment by Fr33maan** [comment]
Ok I thought it was all the power of ignite CLI with the flexibility of expo.
