### ISSUE TITLE
Starting the APP

### ISSUE THREAD

**Issue by Miheegz** [skellock/expo-with-ignite#5]
I added a script for npm start running "react-native-scripts start" however when I run I get a starting packager message and then it stays there indefinitely. Am I starting it wrong is there a different command?

**Comment by skellock** [comment]
i'm not sure what `react-native-scripts start` is?  Is that new in expo?  I haven't used it for a few versions.

**Comment by Miheegz** [comment]
no, thats something i imported. Well how do you start this app?

**Comment by skellock** [comment]
I like to do `exp start` 

https://docs.expo.io/versions/latest/guides/exp-cli.html
